# -*- coding: utf-8 -*-
"""Covid19Indonesia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvFIZAh9pgv2JMzwW8mR1mj0p081cM4J

**Exploratory Data Analysis sederhana pada Data COVID19 Indonesia dengan PYTHON(Pandas dan Matplotlib)**

Link visualisasi tebleau:
https://public.tableau.com/app/profile/frengki1967/viz/Covid19Indonesia_16709812556170/Dashboard1

import dataset covid19 yang sudah dibersihkan
"""

from google.colab import files
upload = files.upload()

"""Import library pandas dan matplot"""

import matplotlib.pyplot as plt
import pandas as pd



"""Buka file yang akan dianalisa"""

covid = pd.read_excel('covid19.xls')
covid

"""Mengecek tipe data"""

covid.dtypes



"""Menambahkan kolom bulan (Month) pada data"""

covid['Month'] = pd.to_datetime(covid["Date"],errors='ignore').dt.strftime('%m')

covid

"""mengahapus kolom bulan """

del covid['Month']

"""Menambahkan kolom tahun(Years) pada data. dimana tahun didapat dari kolom date """

covid['Years'] = pd.to_datetime(covid["Date"],errors='ignore').dt.strftime('%Y')

covid



"""Selanjutya kita akan coba melakukan Filtering sederhana, kita akan coba melakukan filtering pada baris data tertentu, misal pada kolom Location kita ingin menampilkan data covid di jawa timur"""

covidjatim = covid[covid['Location'] == 'Jawa Timur']
covidjatim

"""Selanjutya kita akan coba melakukan Filtering sederhana, kita akan coba melakukan filtering pada covid19 di jawa timur, misal pada kolom years kita ingin menampilkan data covid di jawa timur pada tahun 2022 saja"""

covidjatim2022 = covidjatim[covidjatim['Years'] == '2022']
covidjatim2022



"""Membuat visualisasi terkait covid19 di jawa timur pada tahun 2022"""

plt.plot(covidjatim2022['Date'], covidjatim2022['Total Cases'])
plt.plot(covidjatim2022['Date'], covidjatim2022['Total Recovered'])
plt.plot(covidjatim2022['Date'], covidjatim2022['Total Deaths'])
plt.xticks(rotation = 'vertical')
plt.title('Jumlah korban Covid 19 Jawa Timur pada tahun 2022')
plt.ylabel('jumlah')
plt.xlabel('Tanggal')
plt.legend(['jumlah kasus', 'jumlah sembuh', 'meninggal'])
plt.show()



"""Menghitung kasus covid di setiap provinsi(Total kasus terbaru, total kematian terbaru, total sembuh terbaru )"""

covid_grupby_Location = covid.groupby("Location")

covid_grupby_Location[["New Cases","New Deaths","New Recovered"]].sum()



"""Menghitung kasus covid diindonesia berdasarkan pulau"""

covid_grupby_Island = covid.groupby("Island")

covidpie = covid_grupby_Island[["New Cases","New Deaths","New Recovered"]].sum()

covidpie

covidpie = covid_grupby_Island[["New Cases","New Deaths","New Recovered"]].sum().reset_index()
plt.figure(figsize=(6,6))
plt.legend(['Jawa', 'Sumatera', 'Sulawesi','Nusa Tenggar','Maluku', 'Kalimantan'])
plt.pie(covidpie['New Cases'], 
labels = covidpie['Island'], autopct='%1.2f%%')
plt.title('Kasus covid19 berdasarkan pulau di Indonesia', loc = 'Center',pad=30, fontsize=15, color='Black')
plt.show()

"""Visualisasi grafik kasus harian covid di Indonesia sejak awal muncul covid sampai sekarang"""

plt.plot(covid['Date'], covid['New Cases'],color=)
plt.title('Kasus Covid 19 idonesia')
plt.ylabel('jumlah kasus harian')
plt.xlabel('Tanggal')
plt.xticks(rotation = 'vertical')
plt.show()

"""Visualisasi grafik Orang yang pulih akibat covid di Indonesia sejak awal muncul covid sampai sekarang """

plt.plot(covid['Date'], covid['New Recovered'], color='green')
plt.title('Sembuh akibat Covid 19 indonesia')
plt.ylabel('jumlah sembuh harian')
plt.xlabel('Tanggal')
plt.xticks(rotation = 'vertical')
plt.show()

"""Visualisasi grafik Orang yang meninggal akibat covid di Indonesia sejak awal muncul covid sampai sekarang """

plt.plot(covid['Date'], covid['New Deaths'], color='red')
plt.title('Meninggal akibat Covid 19 indonesia')
plt.ylabel('jumlah meninggal harian')
plt.xlabel('Tanggal')
plt.xticks(rotation = 'vertical')
plt.show()

"""Menampilkan kasus covid19 di Indonesia berdasarkan provinsi"""

keys = [Location for Location, df in covid.groupby(['Location'])]
plt.bar(keys,covid.groupby(['Location']).sum()['New Cases'])
plt.title('Covid 19 indonesia')
plt.ylabel('jumlah kasus dalam juta')
plt.xlabel('Lokasi')
plt.xticks(keys, rotation='vertical', size=8)
plt.show()

"""Menampilkan data keseluruha kasus covid di Indonesia, mulai dari jumlah kasus covid, jumlah meninggal dan jumlah sembuh"""

covid_grupby_Country = covid.groupby("Country")

covidindonesia = covid_grupby_Country[["New Cases","New Deaths","New Recovered"]].sum()
covidindonesia

import matplotlib.pyplot as plt

labels = ['Sembuh', 'Meninggal']
quantity = [6204553, 157819]
colors = ['yellowgreen', 'gold']

plt.title('Covid19 Indonesia')
plt.pie(quantity, labels=labels, colors=colors,
        autopct='%1.1f%%', shadow=True, startangle=50)

plt.axis('equal')
plt.show()

